<article class="infos">
<h2 class="text-danger">Kassensystem BONiFlex</h2>
<p>Professionelle Kassensysteme müssen sich heute in bestehende Betriebsstrukturen einfügen, ohne dabei kompliziert oder unübersichtlich zu wirken. Der Anspruch heute lautet, sofort wirksame Änderungen im laufenden Betrieb vornehmen zu können und das am besten ohne Hinzuziehung von Fachleuten. <strong>BONiFlex</strong> bietet diese und eine Vielzahl weiterer Möglichkeiten, die Sie in Ihrem Betrieb organisatorisch unterstützen und so dazu beitragen, täglich Zeit und bares Geld zu sparen.</p>
<p><strong>BONiFlex</strong> bietet neben den üblichen Funktionen einer Standardkasse eine Reihe zusätzlicher Lösungen, die speziell an die unterschiedlichen Bereiche der Gastronomie angepasst wurden.</p>
<ul>
	<li>Die Abrechnung erfolgt wahlweise über Tisch oder Sofortkasse, wobei bereits eingegebene Bestellungen mit nur einem Tastendruck auf einen Tisch gebucht werden können.</li>Erstellung und Abrechnung von Paketen, die vordefinierte Leistungen und / oder Artikel vollautomatisch kostenfrei oder anteilig abrechnen. Dies bedeutet, dass Pakete eine bestimmte Anzahl verschiedener Artikel enthalten können. Der Gast bestellt das Paket zum Festpreis und wählt (wenn Wahlmöglichkeiten vorgesehen sind) aus den im Paket enthaltenen Artikel diejenigen aus, die ihm zusagen. Wählt der Gast eine größere Anzahl als im Paket enthalten oder nicht im Paket enthaltene Artikel, wird wahlweise die Differenz oder der ganze Artikel berechnet. Wählt er eine geringere Anzahl Artikel, wird der vollständige Paketpreis berechnet.
	<li>Diese Funktion wurde speziell für Spielplätze, Kartbahnen, Kletterhallen usw. geschaffen, die häufiger z. B. Geburtstage oder Veranstaltungen zu einem festen Preis organisieren, bei denen die Gäste dann aus den im Paket enthaltenen Artikel wählen.</li>
	<li>Reservierungsplan mit Check-In-Funktion und Vorabbuchung von Artikeln sowie automatischer Namensübernahme auf die Tische.</li>Pizza-Taxi-Funktion mit Bestellannahme und -auslieferung
	<li>Variantenverwaltung: Buchen Sie Artikel in verschiedenen Varianten (z. B. Cola 0,2 - 0,3 - 0,5 Liter)</li>
	<li>Gutscheinverwaltung: Drucken Sie Gutscheine direkt aus <strong>BONiFlex</strong>. Optional können Kundendaten eingegeben werden und die Gültigkeitsdauer des Gutscheins vom Programm automatisch überwacht werden.</li>Folgeartikel können abhängig von der gebuchten Anzahl des Hauptartikels gebucht werden. Damit ist es nicht nur möglich z. B. Pfand bei Buchung einer Flasche automatisch zu berechnen sondern auch Fälle wie z.B. „2 Freigetränke ab 5 x Eintritt“
	<li>Für Kegelbahnen, Bowlingbahnen usw. können entweder pauschale oder zeitgesteuerte Belegungskosten hinterlegt werden, die bei Belegung des entsprechenden Tisches automatisch berechnet werden.</li>Außer-Haus-Verkauf kann auch positionsbezogen stattfinden. Dadurch ist es nicht mehr notwendig, wie bei herkömmlichen Kassen üblich, einen separaten Außer-Haus-Verkauf zu starten, wenn der Gast einen Teil seiner Bestellung im Haus verzehren und einen anderen Teil der Bestellung mitnehmen möchte. Außer-Haus-Positionen werden auf den Bons entsprechend ausgewiesen.
</ul>
<p>Diese und weitere Punkte unterscheiden <strong>BONiFlex</strong> wesentlich von herkömmlichen Kassensystemen. Selbstverständlich bietet <strong>BONiFlex</strong> von Haus aus alle Standardfunktionen. Um eine komplette Funktionsübersicht zu erhalten klicken Sie hier.</p>
<p>Weiter zur gesamten Funktionsübersicht</p>
</article><!-- infos -->